version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: UPSDataCollection/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      pwr_stat:
        condition: service_healthy
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    #network_mode: host
  api:
    build:
      context: .
      dockerfile: UPSDataAPI/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080" # Maps port 8080 of the host to port 8080 of the container
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: upsdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  pwr_stat:
    container_name: pwr_stat
    hostname: pwr_stat
    restart: always
    image: dwinks/pwrstat_docker:latest
    devices:
      - /dev/bus/usb/002/002:/dev/bus/usb/001/001
    volumes:
      - ./pwrstat.yaml:/pwrstat.yaml:ro
      # Optionally override the powerstatd configuration file
      # - /docker_binds/pwr_stat/pwrstatd.conf:/etc/pwrstatd.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5003/pwrstat"]
      interval: 30s
      timeout: 1s
      retries: 24
    privileged: true
    #network_mode: host
